### ISSUE TITLE
Pickle error when running the example

### ISSUE THREAD

**Issue by AnnaEngel98** [chenwei-zhang/struc2mapGAN#1]
Hello!

After installation and running the example I get a pickle.UnpicklingError, see below:

```
Starting struc2mapGAN...
Traceback (most recent call last):
  File "/trinity/login/aengle/software/struc2mapGAN/app/struc2mapGAN.py", line 126, in <module>
    struc2mapGAN(args)
  File "/trinity/login/aengle/software/struc2mapGAN/app/struc2mapGAN.py", line 103, in struc2mapGAN
    gan_map_path = inference(
  File "/trinity/login/aengle/software/struc2mapGAN/app/inference.py", line 43, in inference
    model = GAN.load_from_checkpoint(ckpt)
  File "/trinity/login/aengle/software/anaconda3/envs/struc2mapGAN/lib/python3.10/site-packages/lightning/pytorch/utilities/model_helpers.py", line 125, in wrapper
    return self.method(cls, *args, **kwargs)
  File "/trinity/login/aengle/software/anaconda3/envs/struc2mapGAN/lib/python3.10/site-packages/lightning/pytorch/core/module.py", line 1581, in load_from_checkpoint
    loaded = _load_from_checkpoint(
  File "/trinity/login/aengle/software/anaconda3/envs/struc2mapGAN/lib/python3.10/site-packages/lightning/pytorch/core/saving.py", line 63, in _load_from_checkpoint
    checkpoint = pl_load(checkpoint_path, map_location=map_location)
  File "/trinity/login/aengle/software/anaconda3/envs/struc2mapGAN/lib/python3.10/site-packages/lightning/fabric/utilities/cloud_io.py", line 57, in _load
    return torch.load(f, map_location=map_location)  # type: ignore[arg-type]
  File "/trinity/login/aengle/software/anaconda3/envs/struc2mapGAN/lib/python3.10/site-packages/torch/serialization.py", line 1040, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/trinity/login/aengle/software/anaconda3/envs/struc2mapGAN/lib/python3.10/site-packages/torch/serialization.py", line 1258, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.
```

**Comment by chenwei-zhang** [comment]
Hi, 
The installation might cause this issue. Please follow the installation guide in README file to create a new conda environment with associated dependencies. 
```
## Create conda environment
conda create -n struc2mapGAN python=3.10
conda activate struc2mapGAN
## Clone git repo
git clone https://github.com/chenwei-zhang/struc2mapGAN.git
cd struc2mapGAN
## Install dependencies
pip install -r requirements.txt
```
After this, you could try to run struc2mapGAN to build your density map. Please let me know if you have any more questions.

**Comment by chenwei-zhang** [comment]
Hi,
I actually updated the requirements.txt file. Could you uninstall the previous version and git clone this repo again and follow the instruction to reinstall.  I tested it in a Linux Ubuntu 20.04 version, and it ran smoothly.

**Comment by chenwei-zhang** [comment]
Hi,
Sorry for still having this issue. I checked carefully and it ran smoothly on my device (Linux Ubuntu). There might be two reasons:
1. The pre-trained model (checkpoint) was not downloaded successfully. I uploaded the checkpoint in Google Drive (https://drive.google.com/file/d/1xReT4R_CeYzCE8u31MES2fTjMk0MflNj/view?usp=drive_link), please feel free to download it and make sure to give the model path correctly.
2. The difference in Linux distribution causes this issue. 

Let me know if you have more questions.
